### ISSUE TITLE
Use of clock_gettime() requires linking with -lrt

### ISSUE THREAD

**Issue by mato** [mirage/mirage-clock#10]
The new PCLOCK implementation for UNIX uses `clock_gettime()`. This requires linking with `-lrt` on some systems. (Including but not limited to the Travis CI environment used for `mirage-skeleton`, see e.g. this build failure: https://travis-ci.org/mirage/mirage-dev/builds/155897982#L471).

**Comment by mato** [comment]
Not sure what the right fix is here, we could either always link against `-lrt` on `unix`, or can we propagate the dependency somehow?
/cc @mattgray @yomimono

**Comment by dbuenzli** [comment]
This should have been fixed see https://github.com/mirage/mirage-clock/issues/8

**Comment by yomimono** [comment]
Should have been (and was for local tests and some Travis builds), but Travis is still failing for mirage-skeleton when trying to link that library. I'll look into it shortly.

**Comment by yomimono** [comment]
Should _really_ be fixed by #11.  Thanks @mato for the accurate diagnosis and (belatedly) @dbuenzli for the pointer to how ptime/mtime handle this.

**Comment by mato** [comment]
This is still not fixed -- manually executing the final `ocamlopt ... -o main.native` command for building `console` with `-verbose` shows `-lmirage-clock-unix_stubs` is present but `-lrt` is not in the link list at all. Also, the failing Travis build for `mirage-dev` still fails.

(Aside: I can't seem to be able to reopen the issue, is that an admin-only thing?)

**Comment by mato** [comment]
The following `Dockerfile` reproduces the problem nicely at `docker build` time:

```
FROM ocaml/opam:ubuntu-12.04_ocaml-4.03.0

RUN opam repo add mirage-dev git://github.com/mirage/mirage-dev
RUN opam depext -i mirage
RUN git clone -b mirage-dev http://github.com/mirage/mirage-skeleton
WORKDIR /home/opam/mirage-skeleton/console
RUN opam config exec -- mirage configure -t unix
RUN opam config exec make
```

**Comment by yomimono** [comment]
Oops, autoclosed _again_.  This really seriously definitely actually looks fixed now with #12 , now that we're trusting `oasis` to do the right thing (as it does with other libraries) rather than trying the custom `myocamlbuild` solution given in #8.  I'll leave this open and let the first convinced person close it.

**Comment by mato** [comment]
I restarted Travis CI for `mirage-dev` and it passed (https://travis-ci.org/mirage/mirage-dev/builds/155912163), so consider it fixed. Thanks!
